import { Providers } from "./providers";


import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: 'Hanover - Sajilo delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <Providers>

            <ToastContainer
              position="top-center"
              theme="light"
              hideProgressBar
              closeOnClick
            />

            {/* <ToastContainer /> */}

            {children}
          </Providers>
        </body>
      </html>
  )
}
